name=STEMBuddy
version=1.0.0
author=Hacktronics / CodeSkool
maintainer=CodeSkool <support@codeskool.cc>
sentence=Turn your phone into virtual hardware for ESP32 projects.
paragraph=STEM Buddy lets your ESP32 control virtual LEDs, LCDs, servos, motors, buzzers, and oscilloscopes on the STEM Buddy Android app over BLE. The app can also send virtual sensor data and button inputs back to your ESP32.
category=Communication
url=https://github.com/hacktronics/STEMBuddy-Arduino
architectures=esp32
includes=STEMBuddy.h
